#!/bin/sh

PRO="obscure-brook-6377"
STG="powerful-ocean-5002"

TMP="./migrations/schema.dump"

case $1 in
  "dev" )
    dropdb --if-exists evercam_dev && createdb evercam_dev \
      && curl -s `heroku pgbackups:url -a $PRO` > $TMP \
      && pg_restore -v -x -O -d evercam_dev < $TMP ;;
  "tst" )
    dropdb --if-exists evercam_tst && createdb evercam_tst \
      && curl -s `heroku pgbackups:url -a $PRO` > $TMP \
      && pg_restore -s -v -x -O -d evercam_tst < $TMP \
      && pg_restore -a -v -x -O -d evercam_tst -t _schema < $TMP ;;
  "stg" )
    heroku pgbackups:restore DATABASE -a $STG \
      `heroku pgbackups:url -a $PRO` ;;
esac

