#!/bin/sh

# pick db command
__get_command () {
  case $1 in
    "dev" )
      echo "psql evercam_dev" ;;
    "tst" )
      echo "psql evercam_tst" ;;
    "stg" )
      echo "heroku pg:psql -a powerful-ocean-5002" ;;
    "pro" )
      echo "heroku pg:psql -a obscure-brook-6377" ;;
  esac
}

# get schema version
__get_current () {
  sql="SELECT value FROM _schema WHERE key = 'VERSION'"
  echo $($1 -A -t -c "$sql" 2>/dev/null)
}

# set schema version
__set_version () {
  $1 -c "UPDATE _schema SET value = '$2' WHERE key = 'VERSION'"
}

dir=$(find -s ./schema -type d | tail -n 1)
command=$(__get_command $1)
current=$(__get_current "$command")
version=$(basename $dir)

# exit unless migrate required
if [ ${current:-0} == $version ]; then
  exit
fi

# pick files to apply
case $1 in
  "dev" | "stg" | "pro")
    files=`ls $dir/*.sql` ;;
  "tst" )
    files=`ls $dir/*.structure.sql` ;;
esac

# apply the sql files
for sql in $files; do
  $command < $sql
done

# update version property
__set_version "$command" $version

