#!/bin/sh

PRO="obscure-brook-6377"
TMP="./migrations/schema.dump"

sudo service postgresql restart

echo ' * Downloading database backup and restoring, please wait...'

dropdb --if-exists evercam_dev \
  && createdb evercam_dev \
  && dropdb --if-exists evercam_tst \
  && createdb evercam_tst \
  && curl -# `heroku pgbackups:url -a $PRO` > $TMP \
  && pg_restore -v -x -O -d evercam_dev < $TMP \
  && pg_restore -s -v -x -O -d evercam_tst < $TMP \
  && pg_restore -a -v -x -O -d evercam_tst -t schema_migrations < $TMP ;
