#!/bin/sh

APP="evercam-api"
TMP="./migrations/schema.dump"

sudo service postgresql restart

echo ' * Downloading database backup and restoring, please wait...'

dropdb --if-exists evercam_dev \
  && createdb evercam_dev \
  && dropdb --if-exists evercam_tst \
  && createdb evercam_tst \
  && curl -# `heroku pg:backups public-url -a $APP` > $TMP \
  && pg_restore -v -x -O -d evercam_dev < $TMP \
  && pg_restore -s -v -x -O -d evercam_tst < $TMP \
  && pg_restore -a -v -x -O -d evercam_tst -t schema_migrations < $TMP ;
