#!/bin/sh
export EVERCAM_ENV="development"
SCHEMA="./migrations/20140117140552.dump"

dropdb --if-exists evercam_dev \
    && createdb evercam_dev \
    && psql evercam_dev < $SCHEMA \
    && psql evercam_dev -c "CREATE EXTENSION postgis;"

# migration fails if run immediately afterwards for some reason
sleep 1

bundle exec rake db:migrate
