#!/bin/sh
SCHEMA="./migrations/20140117140552.dump"

export NO_FAKE_S3="true"

export EVERCAM_ENV="test"

dropdb --if-exists evercam_tst \
    && createdb evercam_tst \
    && psql evercam_tst < $SCHEMA \
    && psql evercam_tst -c "CREATE EXTENSION IF NOT EXISTS postgis;"

export EVERCAM_ENV="development"

dropdb --if-exists evercam_dev \
    && createdb evercam_dev \
    && psql evercam_dev < $SCHEMA \
    && psql evercam_dev -c "CREATE EXTENSION IF NOT EXISTS postgis;"
